server:
  port: 7703

spring:
  application:
    name: Blog-Api-Spring-App-2

  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: Lucky@143

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

#Static User
#  security:
#    user:
#      name: shashi
#      password: password
#      roles: ADMIN

jwt:
  secret: 4dc53f14571acec9adaa29b72614472e1e4ffec50f0ec30a1c910c6b0f1ffa02
  expiry-milliseconds: 14400000